### ISSUE TITLE
Error assertion failed: [width must be <= target - offset]

### ISSUE THREAD

**Issue by subhadeepdas91** [emedvedev/attention-ocr#9]
While training following error occured, assertion failed: [width must be <= target - offset]
Detailed log as follows

aocr train datasets/training.tfrecords

2017-09-14 16:57:11.201375: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-14 16:57:11.201493: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-14 16:57:11,201 root  INFO     loading data
2017-09-14 16:57:11,244 root  INFO     phase: train
2017-09-14 16:57:11,245 root  INFO     model_dir: checkpoints
2017-09-14 16:57:11,245 root  INFO     load_model: True
2017-09-14 16:57:11,245 root  INFO     output_dir: results
2017-09-14 16:57:11,245 root  INFO     steps_per_checkpoint: 100
2017-09-14 16:57:11,245 root  INFO     batch_size: 65
2017-09-14 16:57:11,245 root  INFO     num_epoch: 1000
2017-09-14 16:57:11,246 root  INFO     learning_rate: 1
2017-09-14 16:57:11,246 root  INFO     reg_val: 0
2017-09-14 16:57:11,246 root  INFO     max_gradient_norm: 5.000000
2017-09-14 16:57:11,246 root  INFO     clip_gradients: True
2017-09-14 16:57:11,246 root  INFO     max_image_width 160.000000
2017-09-14 16:57:11,246 root  INFO     max_prediction_length 8.000000
2017-09-14 16:57:11,247 root  INFO     target_vocab_size: 39
2017-09-14 16:57:11,247 root  INFO     target_embedding_size: 10.000000
2017-09-14 16:57:11,247 root  INFO     attn_num_hidden: 128
2017-09-14 16:57:11,247 root  INFO     attn_num_layers: 2
2017-09-14 16:57:11,247 root  INFO     visualize: False
2017-09-14 16:57:19,646 root  INFO     Created model with fresh parameters.
2017-09-14 16:57:22,677 root  INFO     Starting the training process.
2017-09-14 16:57:24.235933: I tensorflow/core/common_runtime/simple_placer.cc:697] Ignoring device specification /device:GPU:0 for node 'map_1/while/foldr/while/TensorArrayReadV3/Enter' because the input edge from 'map_1/while/foldr/TensorArray' is a reference connection and already has a device field set to /job:localhost/replica:0/task:0/device:CPU:0
2017-09-14 16:57:24.236082: I tensorflow/core/common_runtime/simple_placer.cc:697] Ignoring device specification /device:GPU:0 for node 'map_1/while/TensorArrayReadV3/Enter' because the input edge from 'map_1/TensorArray' is a reference connection and already has a device field set to /job:localhost/replica:0/task:0/device:CPU:0
2017-09-14 16:57:24.236550: I tensorflow/core/common_runtime/simple_placer.cc:697] Ignoring device specification /device:GPU:0 for node 'map/while/TensorArrayReadV3/Enter' because the input edge from 'map/TensorArray' is a reference connection and already has a device field set to /job:localhost/replica:0/task:0/device:CPU:0
Traceback (most recent call last):
  File "/home/subhadeep/.local/bin/aocr", line 11, in <module>
    sys.exit(main())
  File "/home/subhadeep/.local/lib/python2.7/site-packages/aocr/__main__.py", line 238, in main
    model.train()
  File "/home/subhadeep/.local/lib/python2.7/site-packages/aocr/model/model.py", line 306, in train
    result = self.step(batch, self.forward_only)
  File "/home/subhadeep/.local/lib/python2.7/site-packages/aocr/model/model.py", line 391, in step
    outputs = self.sess.run(output_feed, input_feed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [width must be <= target - offset]
	 [[Node: map/while/Assert/Assert = Assert[T=[DT_STRING], summarize=3, _device="/job:localhost/replica:0/task:0/cpu:0"](map/while/GreaterEqual, map/while/Assert/Assert/data_0)]]

Caused by op u'map/while/Assert/Assert', defined at:
  File "/home/subhadeep/.local/bin/aocr", line 11, in <module>
    sys.exit(main())
  File "/home/subhadeep/.local/lib/python2.7/site-packages/aocr/__main__.py", line 235, in main
    max_prediction_length=parameters.max_prediction,
  File "/home/subhadeep/.local/lib/python2.7/site-packages/aocr/model/model.py", line 125, in __init__
    self.img_data = tf.map_fn(self._prepare_image, self.img_data, dtype=tf.float32)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/functional_ops.py", line 389, in map_fn
    swap_memory=swap_memory)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2775, in while_loop
    result = context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2604, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2554, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/functional_ops.py", line 379, in compute
    packed_fn_values = fn(packed_values)
  File "/home/subhadeep/.local/lib/python2.7/site-packages/aocr/model/model.py", line 456, in _prepare_image
    padded = tf.image.pad_to_bounding_box(resized, 0, 0, self.height, self.max_width)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/image_ops_impl.py", line 472, in pad_to_bounding_box
    'width must be <= target - offset')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/image_ops_impl.py", line 75, in _assert
    return [control_flow_ops.Assert(cond, [msg])]
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/tf_should_use.py", line 175, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 124, in Assert
    condition, data, summarize, name="Assert")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_logging_ops.py", line 35, in _assert
    summarize=summarize, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): assertion failed: [width must be <= target - offset]
	 [[Node: map/while/Assert/Assert = Assert[T=[DT_STRING], summarize=3, _device="/job:localhost/replica:0/task:0/cpu:0"](map/while/GreaterEqual, map/while/Assert/Assert/data_0)]]

**Comment by emedvedev** [comment]
Make sure you use the most recent version of the package (there was a related bug that's been fixed in the latest version) and that you set `--max-width` and `--max-height` parameters correctly during the training. The default max width is only 160px, which may not be enough for your case.

**Comment by mattfeury** [comment]
FYI i'm still seeing this on occasion as well. Tried to pass the max params in via CLI and also tried to edit model.py directly, but still seeing it. I wrapped the batch loop in a try/catch for now so it will at least continue to train when it seems what i'm assuming is an unexpected image. just wanted to share.

**Comment by emedvedev** [comment]
Weird. The latest version should just discard large images without raising exceptions. If it happens when the training dataset contains a large (>max-width) image which is not being ignored, that's worth a deeper look. Thanks for reporting this.

**Comment by ckirmse** [comment]
I think the problem is that it's discarding images with width > max_width, but later the image will be scaled if height < max_height and the scaled width can be > max_width. I'd suggest re-opening this issue; we can confirm this is the actual issue and fix it assuming it is.

**Comment by reidjohnson** [comment]
I believe updating the `_prepare_image`function  to also resize images that are too wide should correct the problem. Perhaps others could confirm. e.g.:

```python
def _prepare_image(self, image):
    """Resize the image to a maximum height of `self.height` and maximum
    width of `self.width` while maintaining the aspect ratio. Pad the
    resized image to a fixed size of ``[self.height, self.width]``."""
    img = tf.image.decode_png(image, channels=1)
    dims = tf.shape(img)

    if self.data_augment:
        img = self._distort_image(img)

    max_width = tf.to_int32(tf.ceil(tf.truediv(dims[1], dims[0]) * self.height_float))
    max_height = tf.to_int32(tf.ceil(tf.truediv(self.width, max_width) * self.height_float))

    resized = tf.cond(
        tf.greater_equal(self.width, max_width),
        lambda: tf.cond(
            tf.less_equal(dims[0], self.height),
            lambda: tf.to_float(img),
            lambda: tf.image.resize_images(img, [self.height, max_width],
                                           method=tf.image.ResizeMethod.BICUBIC),
        ),
        lambda: tf.image.resize_images(img, [max_height, self.width],
                                       method=tf.image.ResizeMethod.BICUBIC)
    )

    padded = tf.image.pad_to_bounding_box(resized, 0, 0, self.height, self.width)
    return padded
```

**Comment by emedvedev** [comment]
> I think the problem is that it's discarding images with width > max_width, but later the image will be scaled if height < max_height and the scaled width can be > max_width. I'd suggest re-opening this issue; we can confirm this is the actual issue and fix it assuming it is.

If height < max_height, it should just be padded — I was sure I've implemented this already, that's why I'm a little puzzled by this bug. Maybe there's something in the part of the code responsible for padding the image.

> resize the image conditional on both the potential height and width after resizing

I like this idea, except we also need to make sure that people don't try using full-size pictures or anything else of the sort, otherwise it'll first be resized to the degree where the potential text on the pictures wouldn't be recognizable. If the resizing is clearly documented in the README, that could be a good option.

**Comment by reidjohnson** [comment]
I think it's quite a difficult bug to identify, but let's consider an example. The default `IMAGE_HEIGHT` is 32, the default `max_image_width` is 160, and the default `max_image_height` is 60. Let's consider using these defaults to resize an image that is 320 width by 32 height.

Given the defaults, `self.height` and `self.height_float` will be 32 and 32.0, respectively. In `_prepare_image()`, `width` will be computed as ceil((320/32) * 32.0) = 320. Because `dim[0]` = 32 is less than or equal to `self.height` = 32, the variable `resized` will be set to `tf.to_float(image)`. Consequently, the 32x320 image will attempt to be padded to 32x160. Because the image width, 320, is larger than `self.max_width` = 160, the assert `[width must be <= target - offset]` will fail.

If you investigate my suggested code, you'll find that the nested condition statement addresses preventing this assertion failure in a principled way. Of course, my logic could still be wrong, or there may be a simpler solution, so I'd love for others to double-check!

**Comment by reidjohnson** [comment]
Note that in `data_gen.py`, there is an if statement that checks `self.max_width and (Image.open(IO(img)).size[0] <= self.max_width)` to prevent adding images with a width exceeding `self.max_width` from being added to a bucket. However I believe this is executed after the `_prepare_image()` function.

**Comment by mattfeury** [comment]
fyi, i had an image that was able to reliably reproduce this issue and tried your code @reidjohnson and now it is working fine. haven't really dug into the guts of your code, but at a high level it makes sense.

**Comment by ckirmse** [comment]
I've tested it successfully too. I can make a PR if @reidjohnson does not. @emedvedev to help potential users who don't understand that the text needs to be cut out first, maybe we could error out an image if its height and width are **both** too large? That would be easy to put into the dataset creation.

**Comment by emedvedev** [comment]
Erroring out might be a little too much, but a warning would be good, I think. 

Aside from dataset creation, might make sense to put it inside the training so that the user could see if there's a significant portion of the training dataset that's discarded? My reasoning here is that I usually create a dataset first, and then play with maximum width/height during training.

**Comment by ckirmse** [comment]
Ah, that makes total sense. I haven't done much size experimentation yet :).
